#include "browser.h"
#include "core/i18n.h"
#include "core/executor.h"
#include "core/logger.h"
#include "core/config.h"
#include "package_manager.h"
#include <fstream>

namespace tmoe::domain {

BrowserManager::BrowserManager(const TmoeConfig& cfg) : cfg_(cfg) {}

void BrowserManager::run_browser_menu() {
    while (true) {
        std::string menu = cfg_.tui_bin + " --title \"" + _("browser.menu_title")
            + "\" --menu \"" + _("browser.menu_prompt") + "\" 0 0 0 "
            "\"1\" \"" + _("browser.firefox") + "\" "
            "\"2\" \"" + _("browser.chromium") + "\" "
            "\"3\" \"" + _("browser.edge") + "\" "
            "\"4\" \"" + _("browser.falkon") + "\" "
            "\"5\" \"" + _("browser.vivaldi") + "\" "
            "\"6\" \"" + _("browser.midori") + "\" "
            "\"7\" \"" + _("browser.epiphany") + "\" "
            "\"0\" \"" + _("menu.tui.back_upper") + "\"";

        auto ch = Executor::tui_select(menu);
        if (ch == "0" || ch.empty()) break;
        if (ch == "1") install_firefox();
        else if (ch == "2") install_chromium();
        else if (ch == "3") install_edge();
        else if (ch == "4") install_falkon();
        else if (ch == "5") install_vivaldi();
        else if (ch == "6") install_midori();
        else if (ch == "7") install_epiphany();
    }
}

void BrowserManager::install_firefox() {
    auto family = infer_family_from_config(cfg_.linux_distro);
    Logger::step(_("browser.firefox"));

    if (family == DistroFamily::Debian)
        ensure_firefox_ppa();

    PackageManager::install("firefox", family);
    // fallback for older distros
    if (family == DistroFamily::Debian)
        Executor::shell("apt install -y firefox-esr 2>/dev/null || true");
}

void BrowserManager::install_chromium() {
    auto family = infer_family_from_config(cfg_.linux_distro);
    Logger::step(_("browser.chromium"));

    if (family == DistroFamily::Debian)
        ensure_chromium_ppa();

    PackageManager::install("chromium", family);
    if (family == DistroFamily::Debian)
        Executor::shell("apt install -y chromium-browser 2>/dev/null || true");

    Logger::info(_("browser.no_sandbox_info"));
    create_no_sandbox_wrapper("Chromium", "chromium");
}

void BrowserManager::install_edge() {
    auto family = infer_family_from_config(cfg_.linux_distro);
    Logger::step(_("browser.edge"));
    ensure_edge_repo();
    PackageManager::install("microsoft-edge-dev", family);
    Logger::info(_("browser.no_sandbox_info"));
    create_no_sandbox_wrapper("Edge", "microsoft-edge-dev");
}

void BrowserManager::install_falkon() {
    auto family = infer_family_from_config(cfg_.linux_distro);
    Logger::step(_("browser.falkon"));
    PackageManager::install("falkon", family);
    Logger::info(_("browser.no_sandbox_info"));
    create_no_sandbox_wrapper("Falkon", "falkon");
}

void BrowserManager::install_vivaldi() {
    auto family = infer_family_from_config(cfg_.linux_distro);
    Logger::step(_("browser.vivaldi"));
    PackageManager::install("vivaldi-stable", family);
    Logger::info(_("browser.no_sandbox_info"));
    create_no_sandbox_wrapper("Vivaldi", "vivaldi-stable");
}

void BrowserManager::install_midori() {
    auto family = infer_family_from_config(cfg_.linux_distro);
    Logger::step(_("browser.midori"));
    PackageManager::install("midori", family);
}

void BrowserManager::install_epiphany() {
    auto family = infer_family_from_config(cfg_.linux_distro);
    Logger::step(_("browser.epiphany"));
    PackageManager::install("epiphany-browser", family);
}

void BrowserManager::create_no_sandbox_wrapper(const std::string& name,
                                                const std::string& bin_name) {
    bool is_root = cfg_.is_root || cfg_.is_termux;
    if (!is_root && cfg_.linux_distro != "unknown") {
        // 检查当前 uid
        auto id_result = Executor::shell("id -u");
        is_root = id_result.ok() && id_result.stdout_data.find('0') == 0;
    }
    if (!is_root) return;

    Logger::step(_("browser.no_sandbox_wrapper"));

    std::string wrapper_path = "/usr/local/bin/" + bin_name + "--no-sandbox";
    std::string bin_search = (bin_name == "chromium") ? "chromium-browser" : bin_name;

    std::ofstream wrapper(wrapper_path);
    wrapper << "#!/bin/bash\n"
            << "# Auto-generated by tmoe-linux — run " << name << " without sandbox\n\n"
            << "BIN=\"\"\n"
            << "for CANDIDATE in " << bin_name << " " << bin_search << "; do\n"
            << "    if command -v \"$CANDIDATE\" >/dev/null 2>&1; then\n"
            << "        BIN=\"$CANDIDATE\"\n"
            << "        break\n"
            << "    fi\n"
            << "done\n\n"
            << "if [ -z \"$BIN\" ]; then\n"
            << "    echo \"" << name << " not found\" >&2\n"
            << "    exit 1\n"
            << "fi\n\n"
            << "# Check ALSA device env (set by tmoe GUI module)\n"
            << "ALSA_ARGS=\"\"\n"
            << "[ -n \"$ALSODEV\" ] && ALSA_ARGS=\"--alsa-output-device=$ALSODEV\"\n\n"
            << "[ \"$(id -u)\" -eq 0 ] && exec \"$BIN\" --no-sandbox $ALSA_ARGS \"$@\"\n"
            << "exec \"$BIN\" $ALSA_ARGS \"$@\"\n";
    wrapper.close();

    Executor::shell("chmod 755 " + wrapper_path);
    Logger::ok(_("browser.wrapper_created") + ": " + wrapper_path);

    // 创建 .desktop 启动器
    Logger::step(_("browser.no_sandbox_desktop"));
    std::string desktop_dir = "/usr/local/share/applications";
    Executor::shell("mkdir -p " + desktop_dir + " 2>/dev/null");
    std::string desktop_path = desktop_dir + "/" + bin_name + "-no-sandbox.desktop";
    std::ofstream desktop(desktop_path);
    desktop << "[Desktop Entry]\n"
            << "Name=" << name << " (No Sandbox)\n"
            << "Comment=Run " << name << " without sandbox\n"
            << "Exec=" << wrapper_path << "\n"
            << "Type=Application\n"
            << "Categories=Network;WebBrowser;\n"
            << "Terminal=false\n";
    desktop.close();
    Executor::shell("chmod 644 " + desktop_path + " 2>/dev/null");
}

void BrowserManager::ensure_firefox_ppa() {
    Logger::step(_("browser.firefox_ppa"));
    Executor::shell(
        "apt-add-repository -y ppa:mozillateam/ppa 2>/dev/null || "
        "add-apt-repository -y ppa:mozillateam/ppa 2>/dev/null || true"
    );
}

void BrowserManager::ensure_chromium_ppa() {
    Logger::step(_("browser.chromium_ppa"));
    Executor::shell(
        "apt-add-repository -y ppa:saiarcot895/chromium-dev 2>/dev/null || "
        "add-apt-repository -y ppa:saiarcot895/chromium-dev 2>/dev/null || true"
    );
}

void BrowserManager::ensure_edge_repo() {
    Logger::step(_("browser.edge_repo"));
    Executor::shell(
        "if ! dpkg -l | grep -q microsoft-edge; then "
        "  curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor -o "
        "    /etc/apt/trusted.gpg.d/microsoft.gpg 2>/dev/null; "
        "  echo 'deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main' "
        "    > /etc/apt/sources.list.d/microsoft-edge.list 2>/dev/null; "
        "  apt update 2>/dev/null; fi"
    );
}

} // namespace tmoe::domain
