#include "virtualization.h"
#include "core/i18n.h"

namespace tmoe::domain {
    VirtualizationManager::VirtualizationManager(const TmoeConfig &cfg) : cfg_(cfg) {
    }

    // ═══════════════════════════════════════════════════════════════
    //  TUI 主菜单 — 对应 Bash: tools/virtualization/virt-menu
    // ═══════════════════════════════════════════════════════════════

    void VirtualizationManager::run_virt_menu() {
        while (true) {
            std::string menu = cfg_.tui_bin +
                               " --title \"" + _("virt.title") + "\""
                               " --menu \"" + _("virt.menu_prompt") + "\" 0 0 0 "
                               "\"1\" \"" + _("virt.qemu") + "\" "
                               "\"2\" \"" + _("virt.download_iso") + "\" "
                               "\"3\" \"" + _("virt.docker") + "\" "
                               "\"4\" \"" + _("virt.virtualbox") + "\" "
                               "\"5\" \"" + _("virt.wine") + "\" "
                               "\"6\" \"" + _("virt.virt_manager") + "\" "
                               "\"0\" \"" + _("menu.tui.back") + "\"";

            std::string choice = Executor::tui_select(menu);
            if (choice == "0" || choice.empty()) break;

            if (choice == "1") {
                qemu_tui_wizard();
            } else if (choice == "2") {
                run_iso_menu();
            } else if (choice == "3") {
                // Docker 管理委托给 DockerManager
                // 这里输出提示引导到 Docker 菜单
                Logger::info("Docker 管理请在主菜单选择对应选项");
                Logger::info("或通过 CLI: tmoes docker");
            } else if (choice == "4") {
                install_virtualbox();
            } else if (choice == "5") {
                run_wine_menu();
            } else if (choice == "6") {
                install_virt_manager();
            }
            Logger::press_enter();
        }
    }

    // ═══════════════════════════════════════════════════════════════
    //  QEMU 虚拟机管理
    // ═══════════════════════════════════════════════════════════════

    fs::path VirtualizationManager::qemu_dir() const {
        return cfg_.work_dir / "qemu-vms";
    }

    fs::path VirtualizationManager::vm_store_dir() const {
        return qemu_dir();
    }

    void VirtualizationManager::ensure_vm_dir() const {
        fs::create_directories(vm_store_dir());
    }

    bool VirtualizationManager::qemu_create_disk(std::string_view name,
                                                 int64_t size_gb,
                                                 std::string_view format) {
        ensure_vm_dir();
        fs::path disk_path = vm_store_dir() / (std::string(name) + "." + std::string(format));

        std::ostringstream cmd;
        cmd << "qemu-img create -f " << format
                << " \"" << disk_path.string() << "\" " << size_gb << "G";

        auto result = Executor::shell(cmd.str());
        if (result.ok()) {
            Logger::ok("磁盘镜像已创建: " + disk_path.string() + " (" +
                       std::to_string(size_gb) + " GB)");
        }
        return result.ok();
    }

    bool VirtualizationManager::qemu_compress_disk(std::string_view disk_path) {
        Logger::step("压缩 QCOW2 磁盘: " + std::string(disk_path));

        fs::path original(disk_path);
        fs::path compressed = original.parent_path() /
                              (original.stem().string() + "_compressed.qcow2");

        std::string cmd = "qemu-img convert -c -O qcow2 \"" +
                          std::string(disk_path) + "\" \"" +
                          compressed.string() + "\"";
        auto result = Executor::passthrough(cmd);
        if (result.ok()) {
            auto orig_size = fs::file_size(original) / (1024 * 1024);
            auto comp_size = fs::file_size(compressed) / (1024 * 1024);
            Logger::ok("磁盘已压缩: " + std::to_string(orig_size) + " MB → " +
                       std::to_string(comp_size) + " MB");
            Logger::info("压缩后文件: " + compressed.string());
        }
        return result.ok();
    }

    bool VirtualizationManager::qemu_create(std::string_view name,
                                            int64_t disk_size_gb,
                                            int ram_mb, int cpu_cores) {
        Logger::step("创建 QEMU 虚拟机: " + std::string(name));

        ensure_vm_dir();

        // 创建磁盘
        if (!qemu_create_disk(name, disk_size_gb)) {
            return false;
        }

        // 生成启动脚本
        fs::path script_path = vm_store_dir() / (std::string(name) + "_start.sh");
        std::ostringstream script;

        script << "#!/bin/bash\n"
                << "# Auto-generated by tmoes — " << name << "\n\n"
                << "DISK=\"" << vm_store_dir().string() << "/" << name << ".qcow2\"\n"
                << "qemu-system-x86_64 \\\n"
                << "  -machine q35,accel=kvm \\\n"
                << "  -cpu host \\\n"
                << "  -smp sockets=1,cores=" << cpu_cores << ",threads=1 \\\n"
                << "  -m " << ram_mb << " \\\n"
                << "  -drive file=\"$DISK\",if=virtio,format=qcow2 \\\n"
                << "  -vnc :1 \\\n"
                << "  -device virtio-net-pci,netdev=net0 \\\n"
                << "  -netdev user,id=net0\n";

        std::ofstream ofs(script_path);
        if (!ofs) return false;
        ofs << script.str();
        ofs.close();

        // 设置可执行权限
        Executor::shell("chmod +x \"" + script_path.string() + "\"");

        Logger::ok("虚拟机已创建: " + std::string(name));
        Logger::info("启动脚本: " + script_path.string());
        Logger::info("磁盘镜像: " + (vm_store_dir() / (std::string(name) + ".qcow2")).string());

        return true;
    }

    bool VirtualizationManager::qemu_start(std::string_view name) {
        Logger::step("启动 QEMU 虚拟机: " + std::string(name));

        fs::path script = vm_store_dir() / (std::string(name) + "_start.sh");
        if (fs::exists(script)) {
            std::string cmd = "bash \"" + script.string() + "\" &";
            Executor::passthrough(cmd);
            Logger::ok("虚拟机正在启动 (后台)...");
            return true;
        }

        // 尝试直接 QEMU 启动
        fs::path disk = vm_store_dir() / (std::string(name) + ".qcow2");
        if (fs::exists(disk)) {
            std::string cmd = "qemu-system-x86_64 -machine q35,accel=kvm "
                              "-cpu host -m 2048 "
                              "-drive file=\"" + disk.string() + "\",if=virtio "
                              "-vnc :1 -netdev user,id=net0 "
                              "-device virtio-net-pci,netdev=net0 &";
            Executor::passthrough(cmd);
            Logger::ok("虚拟机正在启动 (后台)...");
            Logger::info("VNC 地址: 127.0.0.1:5901");
            return true;
        }

        Logger::error("未找到虚拟机 " + std::string(name) + "，请先使用 qemu_create 创建");
        return false;
    }

    bool VirtualizationManager::qemu_stop(std::string_view name) {
        Logger::step("停止 QEMU 虚拟机...");

        // 通过 qemu monitor 或 kill 发送关机信号
        Executor::shell("pkill -f \"qemu-system.*" + std::string(name) + "\" 2>/dev/null");
        Logger::ok("已发送停止信号");
        return true;
    }

    std::vector<std::string> VirtualizationManager::qemu_list() const {
        std::vector<std::string> result;
        auto exec = Executor::shell("ps aux | grep qemu-system | grep -v grep");
        if (exec.ok()) {
            std::istringstream iss(exec.stdout_data);
            std::string line;
            while (std::getline(iss, line)) {
                if (!line.empty()) result.push_back(line);
            }
        }
        return result;
    }

    bool VirtualizationManager::qemu_tui_wizard() {
        while (true) {
            auto running = qemu_list();

            std::string menu = cfg_.tui_bin +
                               " --title \"" + _("virt.qemu_title") + "\""
                               " --menu \"" + _("virt.qemu_prompt") + " " +
                               std::to_string(running.size()) + "):\" 0 0 0 "
                               "\"1\" \"" + _("virt.qemu_create") + "\" "
                               "\"2\" \"" + _("virt.qemu_start") + "\" "
                               "\"3\" \"" + _("virt.qemu_stop") + "\" "
                               "\"4\" \"" + _("virt.qemu_list") + "\" "
                               "\"5\" \"" + _("virt.qemu_compress") + "\" "
                               "\"0\" \"" + _("menu.tui.back") + "\"";

            std::string choice = Executor::tui_select(menu);
            if (choice == "0" || choice.empty()) break;

            if (choice == "1") {
                // 交互式创建向导
                std::string name_cmd = cfg_.tui_bin +
                                       " --title \"" + _("virt.qemu_name_title") + "\" --inputbox \"" + _("virt.qemu_name_input") + "\" 0 0 \"my-vm\"";
                auto result = Executor::passthrough("echo \"$(" + name_cmd + " 2>&1 1>/dev/tty)\"");
                std::string name = result.stdout_data;
                name.erase(std::remove(name.begin(), name.end(), '\n'), name.end());
                if (name.empty()) continue;

                std::string disk_cmd = cfg_.tui_bin +
                                       " --title \"" + _("virt.qemu_disk_title") + "\" --inputbox \"" + _("virt.qemu_disk_input") + "\" 0 0 \"10\"";
                result = Executor::passthrough("echo \"$(" + disk_cmd + " 2>&1 1>/dev/tty)\"");
                int64_t disk_gb = 10;
                try { disk_gb = std::stoll(result.stdout_data); } catch (...) {
                }

                std::string ram_cmd = cfg_.tui_bin +
                                      " --title \"" + _("virt.qemu_ram_title") + "\" --inputbox \"" + _("virt.qemu_ram_input") + "\" 0 0 \"2048\"";
                result = Executor::passthrough("echo \"$(" + ram_cmd + " 2>&1 1>/dev/tty)\"");
                int ram = 2048;
                try { ram = std::stoi(result.stdout_data); } catch (...) {
                }

                std::string cpu_cmd = cfg_.tui_bin +
                                      " --title \"" + _("virt.qemu_cpu_title") + "\" --inputbox \"" + _("virt.qemu_cpu_input") + "\" 0 0 \"2\"";
                result = Executor::passthrough("echo \"$(" + cpu_cmd + " 2>&1 1>/dev/tty)\"");
                int cpu = 2;
                try { cpu = std::stoi(result.stdout_data); } catch (...) {
                }

                qemu_create(name, disk_gb, ram, cpu);
            } else if (choice == "2") {
                // 列出已有虚拟机让用户选择
                std::vector<std::string> vms;
                for (const auto &entry: fs::directory_iterator(vm_store_dir())) {
                    auto name = entry.path().stem().string();
                    if (name.find("_start") == std::string::npos &&
                        entry.path().extension() == ".qcow2") {
                        vms.push_back(name);
                    }
                }
                if (vms.empty()) {
                    Logger::warn("未找到已创建的虚拟机");
                    continue;
                }
                std::string sub_menu = cfg_.tui_bin +
                                       " --title \"" + _("virt.qemu_select_title") + "\" --menu \"" + _("virt.qemu_select_prompt") + "\" 0 0 0 ";
                for (size_t i = 0; i < vms.size(); ++i) {
                    sub_menu += "\"" + std::to_string(i + 1) + "\" \"" + vms[i] + "\" ";
                }
                sub_menu += "\"0\" \"" + _("menu.tui.back") + "\"";
                std::string sub = Executor::tui_select(sub_menu);
                if (sub != "0" && !sub.empty()) {
                    int idx = std::stoi(sub) - 1;
                    if (idx >= 0 && idx < static_cast<int>(vms.size())) {
                        qemu_start(vms[idx]);
                    }
                }
            } else if (choice == "3") {
                qemu_stop("all");
            } else if (choice == "4") {
                auto list = qemu_list();
                if (list.empty()) {
                    Logger::info("当前无运行中的 QEMU 虚拟机");
                } else {
                    Logger::info("运行中的虚拟机:");
                    for (const auto &l: list) {
                        Logger::info("  " + l);
                    }
                }
            } else if (choice == "5") {
                std::string path_cmd = cfg_.tui_bin +
                                       " --title \"" + _("virt.qemu_disk_path_title") + "\" --inputbox \"" + _("virt.qemu_disk_path_input") + "\" 0 0";
                auto result = Executor::passthrough("echo \"$(" + path_cmd + " 2>&1 1>/dev/tty)\"");
                std::string path = result.stdout_data;
                path.erase(std::remove(path.begin(), path.end(), '\n'), path.end());
                if (!path.empty() && fs::exists(path)) {
                    qemu_compress_disk(path);
                }
            }
            Logger::press_enter();
        }
        return true;
    }

    bool VirtualizationManager::is_qemu_available() const {
        return Executor::has("qemu-system-x86_64") || Executor::has("qemu-system-i386");
    }

    // ═══════════════════════════════════════════════════════════════
    //  ISO / 磁盘镜像下载 — 对应 Bash: tools/virtualization/iso.sh
    // ═══════════════════════════════════════════════════════════════

    std::vector<VirtualizationManager::IsoInfo>
    VirtualizationManager::available_isos() {
        return {
            {
                "alpine",
                "https://dl-cdn.alpinelinux.org/alpine/latest-stable/releases/x86_64/alpine-standard-x86_64.iso",
                "Alpine Linux — 最小体积 (~200MB)"
            },
            {
                "debian", "https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-12.0.0-amd64-netinst.iso",
                "Debian 12 — 网络安装 (~600MB)"
            },
            {
                "ubuntu", "https://releases.ubuntu.com/24.04/ubuntu-24.04-desktop-amd64.iso",
                "Ubuntu 24.04 LTS — 桌面版 (~5GB)"
            },
            {
                "android-x86",
                "https://sourceforge.net/projects/android-x86/files/Release%209.0/android-x86_64-9.0-r2.iso",
                "Android x86_64 9.0"
            },
            {
                "lmde", "https://mirrors.edge.kernel.org/linuxmint/debian/lmde-6-cinnamon-64bit.iso",
                "LMDE 6 — Linux Mint Debian Edition"
            },
        };
    }

    std::vector<std::pair<std::string, std::string> >
    VirtualizationManager::available_disk_templates() {
        return {
            {"alpine-docker", "Alpine Linux + Docker (预构建 qcow2)"},
            {"archlinux", "Arch Linux (预构建 qcow2)"},
            {"debian-sid", "Debian Sid (预构建 qcow2)"},
            {"ubuntu-lts", "Ubuntu LTS (预构建 qcow2)"},
            {"kali", "Kali Linux (预构建 qcow2)"},
        };
    }

    bool VirtualizationManager::download_iso(std::string_view os_name) {
        auto isos = available_isos();
        const IsoInfo *target = nullptr;

        for (const auto &iso: isos) {
            if (iso.name == os_name) {
                target = &iso;
                break;
            }
        }

        if (!target) {
            Logger::error("不支持的 ISO: " + std::string(os_name));
            return false;
        }

        ensure_vm_dir();
        fs::path iso_path = vm_store_dir() / (std::string(os_name) + ".iso");

        Logger::step("下载 " + std::string(os_name) + " ISO...");
        Logger::info("来源: " + target->url);
        Logger::info("保存至: " + iso_path.string());
        Logger::info("(下载大型 ISO 可能需要较长时间)");

        // 使用 wget 或 curl 下载
        std::string dl_cmd = "wget -O \"" + iso_path.string() +
                             "\" \"" + target->url + "\" 2>&1";
        // 如果 wget 不可用，回退到 curl
        if (!Executor::has("wget")) {
            dl_cmd = "curl -L -o \"" + iso_path.string() +
                     "\" \"" + target->url + "\"";
        }

        auto result = Executor::passthrough(dl_cmd);
        if (result.ok() && fs::exists(iso_path)) {
            auto size_mb = fs::file_size(iso_path) / (1024 * 1024);
            Logger::ok("ISO 下载完成: " + iso_path.string() +
                       " (" + std::to_string(size_mb) + " MB)");
            return true;
        }

        Logger::error("ISO 下载失败");
        return false;
    }

    bool VirtualizationManager::download_disk_image(std::string_view template_name) {
        Logger::step("下载预构建磁盘镜像: " + std::string(template_name));
        Logger::info("预构建镜像下载目前需要手动从上游获取");
        Logger::info("推荐使用 alpine-docker 模板快速开始");

        if (template_name == "alpine-docker") {
            ensure_vm_dir();
            // 创建带 Docker 的 Alpine 磁盘
            qemu_create_disk("alpine-docker", 5);

            Logger::info("请使用 QEMU 启动后手动安装 Docker:");
            Logger::info("  qemu-system-x86_64 -cdrom alpine.iso -hda alpine-docker.qcow2");
            Logger::info("然后运行: apk add docker && rc-update add docker boot");
            return true;
        }

        Logger::warn("预构建模板 " + std::string(template_name) + " 暂未实现自动下载");
        return false;
    }

    void VirtualizationManager::run_iso_menu() {
        while (true) {
            auto isos = available_isos();

            std::string menu = cfg_.tui_bin +
                               " --title \"" + _("virt.iso_title") + "\""
                               " --menu \"" + _("virt.iso_prompt") + "\" 0 0 0 ";

            for (size_t i = 0; i < isos.size(); ++i) {
                menu += "\"" + std::to_string(i + 1) + "\" \""
                        + isos[i].name + " — " + isos[i].description + "\" ";
            }

            // 预构建模板
            auto templates = available_disk_templates();
            for (size_t i = 0; i < templates.size(); ++i) {
                menu += "\"" + std::to_string(isos.size() + i + 1) + "\" \""
                        + "[模板] " + templates[i].second + "\" ";
            }

            menu += "\"0\" \"" + _("menu.tui.back") + "\"";

            std::string choice = Executor::tui_select(menu);
            if (choice == "0" || choice.empty()) break;

            int idx = std::stoi(choice) - 1;
            if (idx >= 0 && idx < static_cast<int>(isos.size())) {
                download_iso(isos[idx].name);
            } else {
                int tidx = idx - isos.size();
                if (tidx >= 0 && tidx < static_cast<int>(templates.size())) {
                    download_disk_image(templates[tidx].first);
                }
            }
            Logger::press_enter();
        }
    }

    // ═══════════════════════════════════════════════════════════════
    //  VirtualBox — 对应 Bash: tools/virtualization/vbox.sh
    // ═══════════════════════════════════════════════════════════════

    bool VirtualizationManager::install_virtualbox() {
        Logger::step("安装 VirtualBox...");

        if (is_debian() || is_ubuntu()) {
            // 添加 VirtualBox 软件源
            Executor::passthrough(cfg_.update_command);

            // 安装 VirtualBox
            auto result = Executor::passthrough(cfg_.install_command +
                                          " virtualbox virtualbox-qt virtualbox-ext-pack 2>/dev/null");
            if (!result.ok()) {
                // 如果 ext-pack 导致冲突，只安装基础包
                result = Executor::passthrough(cfg_.install_command + " virtualbox virtualbox-qt");
            }

            if (result.ok()) {
                Logger::ok("VirtualBox 已安装");
                Logger::info("加载内核模块: sudo modprobe vboxdrv");
                return true;
            }
        }

        if (is_arch()) {
            auto result = Executor::passthrough("pacman -S --noconfirm virtualbox virtualbox-host-modules-arch");
            if (result.ok()) {
                Logger::ok("VirtualBox 已安装");
                return true;
            }
        }

        Logger::error("当前发行版不支持自动安装 VirtualBox");
        Logger::info("请手动安装: https://www.virtualbox.org/wiki/Downloads");
        return false;
    }

    bool VirtualizationManager::install_vbox_extension_pack() {
        Logger::step("安装 VirtualBox Extension Pack...");
        auto result = Executor::passthrough(cfg_.install_command + " virtualbox-ext-pack");
        if (result.ok()) {
            Logger::ok("Extension Pack 已安装");
        }
        return result.ok();
    }

    // ═══════════════════════════════════════════════════════════════
    //  Wine — 对应 Bash: tools/virtualization/wine32.sh
    // ═══════════════════════════════════════════════════════════════

    std::vector<std::pair<std::string, std::string> >
    VirtualizationManager::wine_branches() {
        return {
            {"devel", "Wine 开发版 — 最新特性"},
            {"staging", "Wine Staging — 实验补丁"},
            {"stable", "Wine 稳定版"},
        };
    }

    bool VirtualizationManager::install_wine(std::string_view branch) {
        Logger::step("安装 Wine (" + std::string(branch) + ")...");

        if (is_debian() || is_ubuntu()) {
            // 启用 32 位架构
            Executor::passthrough("dpkg --add-architecture i386 2>/dev/null");
            Executor::passthrough(cfg_.update_command);

            // 安装 WineHQ
            auto result = Executor::passthrough(cfg_.install_command +
                                          " wine wine32 wine64 2>/dev/null");

            if (!result.ok()) {
                // 从 WineHQ 官方源安装
                Executor::shell("mkdir -p /etc/apt/keyrings");
                Executor::passthrough("wget -qO- https://dl.winehq.org/wine-builds/winehq.key | "
                    "gpg --dearmor -o /etc/apt/keyrings/winehq-archive-keyring.gpg 2>/dev/null");
                Executor::passthrough(cfg_.update_command);

                result = Executor::passthrough(cfg_.install_command + " --install-recommends "
                                         "winehq-" + std::string(branch) + " wine-" +
                                         std::string(branch) + " wine-" +
                                         std::string(branch) + "-amd64 wine-" +
                                         std::string(branch) + "-i386");
            }

            if (result.ok()) {
                Logger::ok("Wine (" + std::string(branch) + ") 已安装");
                Logger::info("运行 winecfg 进行初始配置");
                return true;
            }
        }

        if (is_arch()) {
            auto result = Executor::passthrough("pacman -S --noconfirm wine");
            if (result.ok()) {
                Logger::ok("Wine 已安装");
                return true;
            }
        }

        // 通用包管理方式
        auto result = Executor::passthrough(cfg_.install_command + " wine 2>/dev/null");
        if (result.ok()) {
            Logger::ok("Wine 已安装");
            return true;
        }

        Logger::error("Wine 安装失败");
        return false;
    }

    bool VirtualizationManager::install_winetricks() {
        Logger::step("安装 Winetricks...");
        auto result = Executor::passthrough(cfg_.install_command + " winetricks");
        if (result.ok()) {
            Logger::ok("Winetricks 已安装");
        } else {
            Logger::warn("Winetricks 安装可能失败，尝试手动下载...");
            Executor::passthrough("wget -O /usr/local/bin/winetricks "
                "https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks 2>/dev/null");
            Executor::shell("chmod +x /usr/local/bin/winetricks");
        }
        return true;
    }

    bool VirtualizationManager::install_dxvk() {
        Logger::step("安装 DXVK (DirectX → Vulkan 转换层)...");
        Logger::info("DXVK 通常通过 Winetricks 安装:");
        Logger::info("  winetricks dxvk");
        return Executor::passthrough("winetricks dxvk 2>/dev/null").ok();
    }

    bool VirtualizationManager::install_playonlinux() {
        Logger::step("安装 PlayOnLinux...");
        return Executor::passthrough(cfg_.install_command + " playonlinux").ok();
    }

    void VirtualizationManager::run_wine_menu() {
        while (true) {
            auto branches = wine_branches();

            std::string menu = cfg_.tui_bin +
                               " --title \"" + _("virt.wine_title") + "\""
                               " --menu \"" + _("virt.wine_prompt") + "\" 0 0 0 "
                               "\"1\" \"" + _("virt.wine_devel") + "\" "
                               "\"2\" \"" + _("virt.wine_staging") + "\" "
                               "\"3\" \"" + _("virt.wine_stable") + "\" "
                               "\"4\" \"" + _("virt.wine_winetricks") + "\" "
                               "\"5\" \"" + _("virt.wine_dxvk") + "\" "
                               "\"6\" \"" + _("virt.wine_playonlinux") + "\" "
                               "\"0\" \"" + _("menu.tui.back") + "\"";

            std::string choice = Executor::tui_select(menu);
            if (choice == "0" || choice.empty()) break;

            if (choice == "1") install_wine("devel");
            else if (choice == "2") install_wine("staging");
            else if (choice == "3") install_wine("stable");
            else if (choice == "4") install_winetricks();
            else if (choice == "5") install_dxvk();
            else if (choice == "6") install_playonlinux();

            Logger::press_enter();
        }
    }

    // ═══════════════════════════════════════════════════════════════
    //  辅助
    // ═══════════════════════════════════════════════════════════════

    bool VirtualizationManager::install_virt_manager() {
        Logger::step("安装 virt-manager (GUI 虚拟化管理器)...");
        auto result = Executor::passthrough(cfg_.install_command +
                                      " virt-manager qemu-kvm libvirt-daemon-system");
        if (result.ok()) {
            Logger::ok("virt-manager 已安装");
            Executor::passthrough("systemctl enable libvirtd 2>/dev/null");
            Executor::passthrough("systemctl start libvirtd 2>/dev/null");
            return true;
        }
        return false;
    }

    std::string VirtualizationManager::os_release() const {
        auto result = Executor::shell("cat /etc/os-release 2>/dev/null | grep '^ID=' | cut -d= -f2");
        std::string rel = result.ok() ? result.stdout_data : "";
        rel.erase(std::remove(rel.begin(), rel.end(), '\n'), rel.end());
        rel.erase(std::remove(rel.begin(), rel.end(), '\"'), rel.end());
        return rel;
    }

    bool VirtualizationManager::is_debian() const {
        return os_release() == "debian";
    }

    bool VirtualizationManager::is_ubuntu() const {
        return os_release() == "ubuntu";
    }

    bool VirtualizationManager::is_arch() const {
        return os_release() == "arch";
    }
} // namespace tmoe::domain
