#include "domain/apps/installable_app.h"
#include "ui/dialog_helpers.h"
#include <filesystem>

namespace fs = std::filesystem;

namespace tmoe::domain {

// ═══════════════════════════════════════════════════════════════
// InstallableApp — 安装管线（模板方法）
// ═══════════════════════════════════════════════════════════════

bool InstallableApp::install(DistroFamily family) {
    Logger::step(name());

    // 1. 安装前钩子（PPA、GPG key 等）
    if (!pre_install(family)) {
        Logger::warn(_("app.install_cancelled") + ": " + name());
        return false;
    }

    // 2. 解析包名并安装
    auto pkgs = packages().get(family);
    if (pkgs.empty()) {
        Logger::error(_f("app.no_packages_for_distro", name()));
        return false;
    }

    if (!PackageManager::install(pkgs, family)) {
        return false;
    }

    // 3. 安装后钩子（配置、wrapper、desktop 等）
    post_install(family);

    // 4. 自动创建 no-sandbox wrapper（如果子类声明需要）
    if (needs_sandbox_wrapper()) {
        create_sandbox_wrapper(name(), bin_name());
    }

    return true;
}

bool InstallableApp::remove(DistroFamily family) {
    // 1. 用户确认
    if (!confirm_remove()) {
        return false;
    }

    // 2. 卸载前钩子
    if (!pre_remove(family)) {
        return false;
    }

    // 3. 执行卸载
    auto pkgs = packages().get(family);
    if (pkgs.empty()) {
        // 尝试用 common 回退
        pkgs = DistroPkgNames::split_pkgs(packages().common);
    }
    PackageManager::remove(pkgs, family);

    // 4. 卸载后清理
    post_remove(family);

    return true;
}

// ═══════════════════════════════════════════════════════════════
// 用户交互
// ═══════════════════════════════════════════════════════════════

bool InstallableApp::confirm_install() {
    // 子类可覆盖以实现特定确认逻辑
    // 默认：始终确认（静默安装）
    return true;
}

bool InstallableApp::confirm_remove() {
    // 使用 dialog::yesno 替代硬编码 whiptail
    return ui::dialog::yesno(cfg_, name(), _f("app.confirm_remove", name()), "", "", 8, 50) == 0;
}

// ═══════════════════════════════════════════════════════════════
// 受保护的辅助方法
// ═══════════════════════════════════════════════════════════════

void InstallableApp::create_sandbox_wrapper(std::string_view display_name,
                                             std::string_view bin) {
    std::string wrapper_path = std::string("/usr/local/bin/") + std::string(bin) + "--no-sandbox";
    std::string bin_str(bin);

    // 写入 wrapper 脚本
    std::string wrapper_content;
    wrapper_content = "#!/bin/bash\n"
                      "# Auto-generated by tmoe-linux — run " + std::string(display_name) +
                      " without sandbox\n\n"
                      "BIN=\"\"\n"
                      "for CANDIDATE in " + bin_str + " " + bin_str + "-browser; do\n"
                      "    if command -v \"$CANDIDATE\" >/dev/null 2>&1; then\n"
                      "        BIN=\"$CANDIDATE\"\n"
                      "        break\n"
                      "    fi\n"
                      "done\n\n"
                      "if [ -z \"$BIN\" ]; then\n"
                      "    echo \"" + std::string(display_name) + " not found\" >&2\n"
                      "    exit 1\n"
                      "fi\n\n"
                      "[ \"$(id -u)\" -eq 0 ] && exec \"$BIN\" --no-sandbox \"$@\"\n"
                      "exec \"$BIN\" \"$@\"\n";

    SystemHelper::write_file(wrapper_path, wrapper_content);
    CommandBuilder("sudo").add_arg("chmod").add_arg("755").add_arg(wrapper_path).execute();
    Logger::ok(_("browser.wrapper_created") + ": " + wrapper_path);

    // 创建 .desktop 文件
    std::string desktop_dir = "/usr/local/share/applications";
    CommandBuilder("sudo").add_arg("mkdir").add_flag("-p").add_arg(desktop_dir)
        .add_raw("2>/dev/null").execute();

    std::string desktop_path = desktop_dir + "/" + bin_str + "-no-sandbox.desktop";
    std::string desktop_content =
        "[Desktop Entry]\n"
        "Name=" + std::string(display_name) + " (No Sandbox)\n"
        "Exec=" + wrapper_path + "\n"
        "Icon=" + bin_str + "\n"
        "Type=Application\n"
        "Categories=Network;WebBrowser;\n"
        "Terminal=false\n";

    SystemHelper::write_file(desktop_path, desktop_content);
    CommandBuilder("sudo").add_arg("chmod").add_arg("644").add_arg(desktop_path)
        .add_raw("2>/dev/null").execute();

    // 复制到桌面
    std::string home = std::getenv("HOME") ? std::getenv("HOME") : "/root";
    CommandBuilder("mkdir").add_flag("-p").add_arg(home + "/Desktop")
        .add_raw("2>/dev/null").execute();
    CommandBuilder("cp").add_flag("-f").add_arg(desktop_path)
        .add_arg(home + "/Desktop/").add_raw("2>/dev/null || true").execute();

    // 如果有 SUDO_USER，也复制到对应桌面
    std::string sudo_user = std::getenv("SUDO_USER") ? std::getenv("SUDO_USER") : "";
    if (!sudo_user.empty() && sudo_user != "root") {
        CommandBuilder("sudo").add_arg("cp").add_flag("-f").add_arg(desktop_path)
            .add_arg("/home/" + sudo_user + "/Desktop/")
            .add_raw("2>/dev/null || true").execute();
    }
}

void InstallableApp::create_desktop_entry(std::string_view app_name,
                                           std::string_view exec_path,
                                           std::string_view icon_name,
                                           std::string_view categories) {
    std::string desktop_dir = "/usr/local/share/applications";
    CommandBuilder("sudo").add_arg("mkdir").add_flag("-p").add_arg(desktop_dir)
        .add_raw("2>/dev/null").execute();

    // 用可执行文件路径生成唯一文件名
    std::string filename;
    for (char c : exec_path) {
        if (c == '/' || c == '\\') filename += '-';
        else filename += c;
    }
    std::string desktop_path = desktop_dir + "/" + filename + ".desktop";

    std::string desktop_content =
        "[Desktop Entry]\n"
        "Name=" + std::string(app_name) + "\n"
        "Exec=" + std::string(exec_path) + "\n"
        "Icon=" + std::string(icon_name) + "\n"
        "Type=Application\n"
        "Categories=" + std::string(categories) + "\n"
        "Terminal=false\n";

    SystemHelper::write_file(desktop_path, desktop_content);
    CommandBuilder("sudo").add_arg("chmod").add_arg("644").add_arg(desktop_path)
        .add_raw("2>/dev/null").execute();

    Logger::ok(_("browser.wrapper_created") + ": " + desktop_path);
}

} // namespace tmoe::domain
