# embed_json.cmake
cmake_minimum_required(VERSION 3.12)

# 参数校验
if(NOT DEFINED INPUT_FILE OR NOT DEFINED OUTPUT_FILE OR NOT DEFINED VAR_NAME)
    message(FATAL_ERROR "Usage: cmake -DINPUT_FILE=<in> -DOUTPUT_FILE=<out> -DVAR_NAME=<name> -P embed_json.cmake")
endif()

# 1. 确保输入文件存在
if(NOT EXISTS "${INPUT_FILE}")
    message(FATAL_ERROR "Input file not found: ${INPUT_FILE}")
endif()

# 2. 以十六进制连续读取整个文件
file(READ "${INPUT_FILE}" hex_string HEX)

# 3. 通过正则替换，将其格式化为 C++ 的十六进制数组 (如 "0x7b, 0x22, ...")
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "static_cast<char>(0x\\1), " hex_array "${hex_string}")

# 4. 拼接 C++ 头文件内容
set(H_CONTENT "// AUTO-GENERATED by embed_json.cmake — do not edit\n")
string(APPEND H_CONTENT "#pragma once\n#include <string_view>\n\n")
string(APPEND H_CONTENT "namespace tmoe::gen {\n\n")
string(APPEND H_CONTENT "    constexpr char ${VAR_NAME}_data[] = { ${hex_array} };\n")
string(APPEND H_CONTENT "    constexpr std::string_view ${VAR_NAME}(${VAR_NAME}_data, sizeof(${VAR_NAME}_data));\n\n")
string(APPEND H_CONTENT "} // namespace tmoe::gen\n")

# 5. 确保输出目录存在并写入
get_filename_component(OUT_DIR "${OUTPUT_FILE}" DIRECTORY)
if(NOT "${OUT_DIR}" STREQUAL "")
    file(MAKE_DIRECTORY "${OUT_DIR}")
endif()
file(WRITE "${OUTPUT_FILE}" "${H_CONTENT}")

message(STATUS "Embedded JSON as '${VAR_NAME}' into ${OUTPUT_FILE}")