# embed_i18n.cmake
cmake_minimum_required(VERSION 3.12)

# 参数校验
if(NOT DEFINED LOCALES_DIR OR NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "Usage: cmake -DLOCALES_DIR=<dir> -DOUTPUT_FILE=<file> -P embed_i18n.cmake")
endif()

file(GLOB json_files "${LOCALES_DIR}/*.json")
if(NOT json_files)
    message(WARNING "No JSON files found in ${LOCALES_DIR}")
endif()

# 初始化 C++ 头文件内容
set(H_CONTENT "// AUTO-GENERATED by embed_i18n.cmake — do not edit\n")
string(APPEND H_CONTENT "#pragma once\n#include <string_view>\n#include <unordered_map>\n\nnamespace tmoe::i18n::embedded {\n\n")

set(LANG_ENTRIES "")
set(FIRST_LANG "")

# 1. 遍历读取数据
foreach(f IN LISTS json_files)
    get_filename_component(lang "${f}" NAME_WE)
    if(FIRST_LANG STREQUAL "")
        set(FIRST_LANG "${lang}")
    endif()

    # 核心黑科技：直接将文件以连续的十六进制字符串读入 (如 "7b226e61...")
    file(READ "${f}" hex_string HEX)

    # 核心黑科技：通过正则替换，将其格式化为 C++ 的十六进制数组 (如 "0x7b, 0x22, ...")
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "static_cast<char>(0x\\1), " hex_array "${hex_string}")

    string(APPEND H_CONTENT "    constexpr char ${lang}_data[] = { ${hex_array} };\n")
    string(APPEND H_CONTENT "    constexpr std::string_view ${lang}(${lang}_data, sizeof(${lang}_data));\n\n")
    string(APPEND LANG_ENTRIES "        {\"${lang}\", ${lang}},\n")
endforeach()

# 2. 写入语言注册表
string(APPEND H_CONTENT "    // ── 语言注册 ──\n")
string(APPEND H_CONTENT "    inline const std::unordered_map<std::string_view, std::string_view> LANGS = {\n${LANG_ENTRIES}    };\n\n")

# 处理默认语言兜底
set(DEFAULT_LANG "en_US")
# 如果实际文件列表中没有 en_US，则使用第一个找到的语言
list(FIND json_files "${LOCALES_DIR}/${DEFAULT_LANG}.json" has_en)
if(has_en EQUAL -1 AND NOT FIRST_LANG STREQUAL "")
    set(DEFAULT_LANG "${FIRST_LANG}")
endif()

string(APPEND H_CONTENT "    inline constexpr std::string_view DEFAULT_LANG = \"${DEFAULT_LANG}\";\n\n")
string(APPEND H_CONTENT "} // namespace tmoe::i18n::embedded\n")

# 3. 确保存储目录存在并写入文件
get_filename_component(OUT_DIR "${OUTPUT_FILE}" DIRECTORY)
file(MAKE_DIRECTORY "${OUT_DIR}")
file(WRITE "${OUTPUT_FILE}" "${H_CONTENT}")

message(STATUS "Embedded ${LOCALES_DIR} to ${OUTPUT_FILE}")