#!/usr/bin/env python3
"""将 locales/ 下的 JSON 编译为十六进制 C++ 头文件嵌入二进制。"""
import json
import sys
from pathlib import Path

def main():
    if len(sys.argv) != 3:
        print("Usage: embed_i18n.py <locales_dir> <output_file>")
        sys.exit(1)

    locales_dir = Path(sys.argv[1])
    output_file = Path(sys.argv[2])

    # 1. 遍历读取数据
    langs = {}
    for f in sorted(locales_dir.glob("*.json")):
        lang = f.stem
        with open(f, 'r', encoding='utf-8') as fp:
            langs[lang] = json.load(fp)

    # 2. 确保输出目录存在
    output_file.parent.mkdir(parents=True, exist_ok=True)

    # 3. 写入 C++ 代码
    with open(output_file, 'w', encoding='utf-8') as fp:
        fp.write("// AUTO-GENERATED by embed_i18n.py — do not edit\n")
        fp.write("#pragma once\n")
        fp.write("#include <string_view>\n")
        fp.write("#include <unordered_map>\n\n")
        fp.write("namespace tmoe::i18n::embedded {\n\n")

        # 将每个语言的 JSON 转化为 char 数组
        for lang, data in langs.items():
            json_str = json.dumps(data, separators=(',', ':'))
            hex_array = ', '.join([f"0x{b:02x}" for b in json_str.encode('utf-8')])

            fp.write(f"    constexpr char {lang}_data[] = {{ {hex_array} }};\n")
            fp.write(f"    constexpr std::string_view {lang}({lang}_data, sizeof({lang}_data));\n\n")

        # 语言注册表
        fp.write("    // ── 语言注册 ──\n")
        fp.write("    inline const std::unordered_map<std::string_view, std::string_view> LANGS = {\n")
        for lang in langs:
            fp.write(f'        {{"{lang}", {lang}}},\n')
        fp.write("    };\n\n")

        # 默认语言
        default = "en_US" if "en_US" in langs else (list(langs.keys())[0] if langs else "en_US")
        fp.write(f'    inline constexpr std::string_view DEFAULT_LANG = "{default}";\n\n')

        fp.write("} // namespace tmoe::i18n::embedded\n")

    print(f"  Embedded {len(langs)} language(s): {', '.join(langs)}")


if __name__ == "__main__":
    main()