# embed_i18n.cmake — 直接将 JSON 以 raw string literal 嵌入，避免 HEX 膨胀
cmake_minimum_required(VERSION 3.12)

if(NOT DEFINED LOCALES_DIR OR NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "Usage: cmake -DLOCALES_DIR=<dir> -DOUTPUT_FILE=<file> -P embed_i18n.cmake")
endif()

file(GLOB json_files "${LOCALES_DIR}/*.json")
if(NOT json_files)
    message(WARNING "No JSON files found in ${LOCALES_DIR}")
endif()

set(H_CONTENT "// AUTO-GENERATED by embed_i18n.cmake — do not edit\n")
set(H_CONTENT "${H_CONTENT}#pragma once\n#include <string_view>\n#include <unordered_map>\n\n")
set(H_CONTENT "${H_CONTENT}namespace tmoe::i18n::embedded {\n\n")

set(LANG_ENTRIES "")
set(FIRST_LANG "")

foreach(f IN LISTS json_files)
    get_filename_component(lang "${f}" NAME_WE)
    if(FIRST_LANG STREQUAL "")
        set(FIRST_LANG "${lang}")
    endif()

    file(READ "${f}" json_content)
    set(H_CONTENT "${H_CONTENT}    inline constexpr std::string_view ${lang} = R\"i18n(\n")
    set(H_CONTENT "${H_CONTENT}${json_content}")
    set(H_CONTENT "${H_CONTENT}\n)i18n\";\n\n")
    set(LANG_ENTRIES "${LANG_ENTRIES}        {\"${lang}\", ${lang}},\n")
endforeach()

set(H_CONTENT "${H_CONTENT}    // ── 语言注册 ──\n")
set(H_CONTENT "${H_CONTENT}    inline const std::unordered_map<std::string_view, std::string_view> LANGS = {\n${LANG_ENTRIES}    };\n\n")

set(DEFAULT_LANG "en_US")
list(FIND json_files "${LOCALES_DIR}/${DEFAULT_LANG}.json" has_en)
if(has_en EQUAL -1 AND NOT FIRST_LANG STREQUAL "")
    set(DEFAULT_LANG "${FIRST_LANG}")
endif()

set(H_CONTENT "${H_CONTENT}    inline constexpr std::string_view DEFAULT_LANG = \"${DEFAULT_LANG}\";\n\n")
set(H_CONTENT "${H_CONTENT}} // namespace tmoe::i18n::embedded\n")

file(WRITE "${OUTPUT_FILE}" "${H_CONTENT}")
message(STATUS "Embedded i18n data into ${OUTPUT_FILE}")
