# embed_json.cmake — 直接将 JSON 以 raw string literal 嵌入，避免 HEX 膨胀
cmake_minimum_required(VERSION 3.12)

if(NOT DEFINED INPUT_FILE OR NOT DEFINED OUTPUT_FILE OR NOT DEFINED VAR_NAME)
    message(FATAL_ERROR "Usage: cmake -DINPUT_FILE=<in> -DOUTPUT_FILE=<out> -DVAR_NAME=<name> -P embed_json.cmake")
endif()

if(NOT EXISTS "${INPUT_FILE}")
    message(FATAL_ERROR "Input file not found: ${INPUT_FILE}")
endif()

file(READ "${INPUT_FILE}" json_content)

set(H_CONTENT "// AUTO-GENERATED by embed_json.cmake — do not edit\n")
set(H_CONTENT "${H_CONTENT}#pragma once\n#include <string_view>\n\n")
set(H_CONTENT "${H_CONTENT}namespace tmoe::gen {\n\n")
set(H_CONTENT "${H_CONTENT}    inline constexpr std::string_view ${VAR_NAME} = R\"json(\n")
set(H_CONTENT "${H_CONTENT}${json_content}")
set(H_CONTENT "${H_CONTENT}\n)json\";\n\n")
set(H_CONTENT "${H_CONTENT}} // namespace tmoe::gen\n")

file(WRITE "${OUTPUT_FILE}" "${H_CONTENT}")
message(STATUS "Embedded JSON as '${VAR_NAME}' into ${OUTPUT_FILE}")
