#!/usr/bin/env python3
"""将单个 JSON 文件编译为十六进制 C++ 头文件嵌入二进制。"""
import json
import sys
from pathlib import Path

def main():
    if len(sys.argv) != 4:
        print("Usage: embed_json.py <input.json> <output.h> <var_name>")
        sys.exit(1)

    input_file = Path(sys.argv[1])
    output_file = Path(sys.argv[2])
    var_name = sys.argv[3]

    # 1. 读取数据
    with open(input_file, 'r', encoding='utf-8') as f:
        data = json.load(f)

    # 2. 压缩 JSON 并转化为 Hex 字节流
    json_str = json.dumps(data, separators=(',', ':'))
    hex_array = ', '.join([f"0x{b:02x}" for b in json_str.encode('utf-8')])

    # 3. 确保输出目录存在
    output_file.parent.mkdir(parents=True, exist_ok=True)

    # 4. 写入 C++ 代码
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write("// AUTO-GENERATED by embed_json.py — do not edit\n")
        f.write("#pragma once\n")
        f.write("#include <string_view>\n\n")
        f.write("namespace tmoe::gen {\n\n")
        f.write(f"    constexpr char {var_name}_data[] = {{ {hex_array} }};\n")
        f.write(f"    constexpr std::string_view {var_name}({var_name}_data, sizeof({var_name}_data));\n\n")
        f.write("} // namespace tmoe::gen\n")

    print(f"  Embedded JSON as '{var_name}' into {output_file.name}")


if __name__ == "__main__":
    main()